### ISSUE TITLE
Will the i915 hwconfig patch be upstreamed to Mesa

### ISSUE THREAD

**Issue by shibdas** [intel-gpu/Mesa#1]
Hi,
       @jljusten, Do you plan to upstream https://github.com/intel-gpu/Mesa/commit/d0e065bda4c5d093c29292f3aed6a5a5fba3fa57 public Mesa? We need for intel driver to work in photon OS with 5.10 kernel but would like to use upstream mesa. Thanks!

**Comment by jljusten** [comment]
@shibdas: Unfortunately not. The "prelim" interfaces are a fork of the Linux uapi, and cannot be supported by upstream Linux. The upstream Mesa project only supports the upstream Linux uapi.

The Mesa tags posted here are rebased onto recent upstream Mesa, and should support the i915-prelim forked Linux interfaces, in addition to the upstream Linux uapi.

DG2 motherboard down devices are supported by upstream Linux 5.19 and Mesa 22.1, and add-in-cards with Linux 6.0 and Mesa 22.2. (But, the kernel may require a command line override to enable support.)

Of course, the later releases of Linux and Mesa are generally better.

**Comment by shibdas** [comment]
@jljusten Is the patch https://github.com/intel-gpu/Mesa/commit/d0e065bda4c5d093c29292f3aed6a5a5fba3fa57 along with header from https://github.com/intel-gpu/drm-uapi-helper/blob/master/drm-uapi/i915_drm_prelim.h on top of upstream Mesa is enough to support DG2 on 5.10 kernel? Is something else needed? Instead of using an async forked repo, we are looking at mostly using upstream mesa with a small patch to support DG2 in photon OS

**Comment by jljusten** [comment]
> @jljusten Is the patch [d0e065b](https://github.com/intel-gpu/Mesa/commit/d0e065bda4c5d093c29292f3aed6a5a5fba3fa57) along with header from https://github.com/intel-gpu/drm-uapi-helper/blob/master/drm-uapi/i915_drm_prelim.h on top of upstream Mesa is enough to support DG2 on 5.10 kernel? Is something else needed? Instead of using an async forked repo, we are looking at mostly using upstream mesa with a small patch to support DG2 in photon OS

If you look at the history for the most recent tag:

https://github.com/intel-gpu/Mesa/commits/dg2-20230125

there are 11 patches in the START / END dii-prelim section. The pci-id one could possibly be skipped as I don't think those are generally available outside of Intel.

There's quite a few other patches in these tags, but those are the most essential for working with the forked Linux uapi available in some kernel trees. (likely the 5.10 tree you are referring to)

We don't test a minimal Mesa upstream + just those patches, so I'm not sure what issues might arise.

**Comment by shibdas** [comment]
Ah, I see. Thanks so much! One more question, these released tags are tested extensively on DG2 separately than upstream mesa I presume?

**Comment by jljusten** [comment]
There is another team at Intel that tests these tags on the "forked" Linux kernel.

My team also tests these tags on an upstream Linux kernel.

Of course, at this point the majority of testing happens with upstream Linux and upstream Mesa. (so, not using these tags)
