### ISSUE TITLE
will intel flex gpu be made upstream mesa compatible?

### ISSUE THREAD

**Issue by z0Kng** [intel-gpu/Mesa#2]
I have noticed that intel flex gpus do not work properly with upstream mesa, but they do work with this mesa. Are there plans to make them compatible with upstream mesa?

**Comment by jljusten2** [comment]
I think you are asking if upstream Mesa will be compatible with the kernels under:

https://github.com/intel-gpu/intel-gpu-i915-backports

which supports a forked (non-upstream) Linux uapi:

https://github.com/intel-gpu/drm-uapi-helper

Unfortunately, upstream Mesa only supports the upstream Linux uapi, so it won't support those kernels.

The Mesa tags in this repo support both kernels. (with either the upstream uapi, or forked uapi.)
